<?php

namespace Database\Seeders;

use App\Models\RefKantorBC;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class RefKantorBCSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$now = Carbon::now('utc')->toDateTimeString();
		$data = [
			[
				'tipe' => 1,
				'level' => 1,
				'parent' => null,
				'kd_kantor' => '000000',
				'nama_kantor' => 'DIREKTORAT JENDERAL BEA DAN CUKAI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 2,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '001000',
				'nama_kantor' => 'SEKRETARIAT DIREKTORAT JENDERAL',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 3,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '001100',
				'nama_kantor' => 'TENAGA PENGKAJI BIDANG I',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 3,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '001200',
				'nama_kantor' => 'TENAGA PENGKAJI BIDANG II',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 3,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '001300',
				'nama_kantor' => 'TENAGA PENGKAJI BIDANG III',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '001400',
				'nama_kantor' => 'DIREKTORAT KEPATUHAN INTERNAL',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '002000',
				'nama_kantor' => 'DIREKTORAT TEKNIS KEPABEANAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '003000',
				'nama_kantor' => 'DIREKTORAT FASILITAS KEPABEANAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '004000',
				'nama_kantor' => 'DIREKTORAT TEKNIS DAN FASILITAS CUKAI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '005000',
				'nama_kantor' => 'DIREKTORAT PENINDAKAN DAN PENYIDIKAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '006000',
				'nama_kantor' => 'DIREKTORAT AUDIT KEPABEANAN DAN CUKAI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '007000',
				'nama_kantor' => 'DIREKTORAT KEPABEANAN INTERNASIONAL DAN ANTAR LEMBAGA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '008000',
				'nama_kantor' => 'DIREKTORAT PENERIMAAN DAN PERENCANAAN STRATEGIS',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '001500',
				'nama_kantor' => 'DIREKTORAT KEBERATAN BANDING DAN PERATURAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 4,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '009000',
				'nama_kantor' => 'DIREKTORAT INFORMASI KEPABEANAN DAN CUKAI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 5,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '040300',
				'nama_kantor' => 'KANTOR PELAYANAN UTAMA BEA DAN CUKAI TIPE A TANJUNG PRIOK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 5,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '020400',
				'nama_kantor' => 'KANTOR PELAYANAN UTAMA BEA DAN CUKAI TIPE B BATAM',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 5,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '050100',
				'nama_kantor' => 'KANTOR PELAYANAN UTAMA BEA DAN CUKAI TIPE C SOEKARNO-HATTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '130000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC ACEH',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '130000',
				'kd_kantor' => '130300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C SABANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '130000',
				'kd_kantor' => '130100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BANDA ACEH',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '130000',
				'kd_kantor' => '130400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MEULABOH',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '130000',
				'kd_kantor' => '130500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C LHOKSEUMAWE',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '130000',
				'kd_kantor' => '130600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C KUALA LANGSA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '010000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC SUMATERA UTARA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '010700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN BELAWAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '010800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B MEDAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '011000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PEMATANGSIANTAR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '011300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C SIBOLGA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '011100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C TELUK NIBUNG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '011200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C KUALA TANJUNG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '010100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B KUALANAMU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 8,
				'level' => 3,
				'parent' => '010000',
				'kd_kantor' => '011600',
				'nama_kantor' => 'BALAI PENGUJIAN DAN IDENTIFIKASI BARANG TIPE B MEDAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '140000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC RIAU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '140000',
				'kd_kantor' => '021200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B PEKANBARU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '140000',
				'kd_kantor' => '020900',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B DUMAI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '140000',
				'kd_kantor' => '021500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C TEMBILAHAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '140000',
				'kd_kantor' => '021100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BENGKALIS',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 9,
				'level' => 3,
				'parent' => '140000',
				'kd_kantor' => '021800',
				'nama_kantor' => 'PANGKALAN SARANA OPERASI BEA DAN CUKAI TIPE B BATAM',
				'active' => false,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '020000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC KHUSUS KEPULAUAN RIAU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '020000',
				'kd_kantor' => '020100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B TANJUNG BALAI KARIMUN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '020000',
				'kd_kantor' => '020500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B TANJUNGPINANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 9,
				'level' => 3,
				'parent' => '020000',
				'kd_kantor' => '021900',
				'nama_kantor' => 'PANGKALAN SARANA OPERASI BEA DAN CUKAI TIPE A TANJUNG BALAI KARIMUN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '030000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC SUMATERA BAGIAN TIMUR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '030000',
				'kd_kantor' => '030100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B PALEMBANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '030000',
				'kd_kantor' => '030600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B JAMBI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '030000',
				'kd_kantor' => '030300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PANGKALPINANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '030000',
				'kd_kantor' => '030500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C TANJUNGPANDAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '170000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC SUMATERA BAGIAN BARAT',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '170000',
				'kd_kantor' => '011500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B TELUK BAYUR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '170000',
				'kd_kantor' => '030200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BENGKULU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '170000',
				'kd_kantor' => '030700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B BANDAR LAMPUNG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '150000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC BANTEN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '150000',
				'kd_kantor' => '050400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN MERAK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '150000',
				'kd_kantor' => '150300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A TANGERANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '040000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC JAKARTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '040000',
				'kd_kantor' => '040400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A JAKARTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '040000',
				'kd_kantor' => '160200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A MARUNDA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '040000',
				'kd_kantor' => '040600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C KANTOR POS PASAR BARU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 8,
				'level' => 3,
				'parent' => '040000',
				'kd_kantor' => '040500',
				'nama_kantor' => 'BALAI PENGUJIAN DAN IDENTIFIKASI BARANG TIPE A JAKARTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 9,
				'level' => 3,
				'parent' => '040000',
				'kd_kantor' => '040700',
				'nama_kantor' => 'PANGKALAN SARANA OPERASI BEA DAN CUKAI TIPE B TANJUNG PRIOK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '050000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC JAWA BARAT',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '050000',
				'kd_kantor' => '050900',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A BEKASI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '050000',
				'kd_kantor' => '050300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A BOGOR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '050000',
				'kd_kantor' => '050800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A PURWAKARTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '050000',
				'kd_kantor' => '050500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A BANDUNG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '050000',
				'kd_kantor' => '050700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C CIREBON',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '050000',
				'kd_kantor' => '050600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C TASIKMALAYA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '050000',
				'kd_kantor' => '051000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN CIKARANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '060000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC JAWA TENGAH DAN D.I. YOGYAKARTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '060100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN TANJUNG EMAS',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '060300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA CUKAI KUDUS',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '060600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B SURAKARTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '060400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C CILACAP',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '062000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PURWOKERTO',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '061000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C TEGAL',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '060800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A SEMARANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '060700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B YOGYAKARTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '060000',
				'kd_kantor' => '061100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MAGELANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '070000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC JAWA TIMUR I',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '070100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN TANJUNG PERAK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '071300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A PASURUAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '070500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN JUANDA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '070300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B GRESIK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '070200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MADURA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '070400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BOJONEGORO',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '071500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B SIDOARJO',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 8,
				'level' => 3,
				'parent' => '070000',
				'kd_kantor' => '071400',
				'nama_kantor' => 'BALAI PENGUJIAN DAN IDENTIFIKASI BARANG TIPE B SURABAYA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '160000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC JAWA TIMUR II',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '160000',
				'kd_kantor' => '070600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA CUKAI MALANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '160000',
				'kd_kantor' => '070800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA CUKAI KEDIRI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '160000',
				'kd_kantor' => '070700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BLITAR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '160000',
				'kd_kantor' => '071000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MADIUN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '160000',
				'kd_kantor' => '071100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C JEMBER',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '160000',
				'kd_kantor' => '160700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BANYUWANGI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '160000',
				'kd_kantor' => '071200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PROBOLINGGO',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '080000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC BALI, NTB DAN NTT',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '080000',
				'kd_kantor' => '080100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN NGURAH RAI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '080000',
				'kd_kantor' => '080200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN A DENPASAR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '080000',
				'kd_kantor' => '080300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MATARAM',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '080000',
				'kd_kantor' => '080400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C SUMBAWA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '080000',
				'kd_kantor' => '080500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C KUPANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '080000',
				'kd_kantor' => '081400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B ATAMBUA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '080000',
				'kd_kantor' => '080700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MAUMERE',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '090000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC KALIMANTAN BAGIAN BARAT',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '090000',
				'kd_kantor' => '090100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B PONTIANAK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '090000',
				'kd_kantor' => '090200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C ENTIKONG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '090000',
				'kd_kantor' => '091000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C NANGA BADAU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '090000',
				'kd_kantor' => '090500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C SINTETE',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '090000',
				'kd_kantor' => '090400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C KETAPANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '090000',
				'kd_kantor' => '092000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C JAGOI BABANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '180000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC KALIMANTAN BAGIAN SELATAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '180000',
				'kd_kantor' => '100100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B BANJARMASIN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '180000',
				'kd_kantor' => '090700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C SAMPIT',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '180000',
				'kd_kantor' => '090800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PANGKALAN BUN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '180000',
				'kd_kantor' => '090900',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PULANG PISAU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '180000',
				'kd_kantor' => '100200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C KOTABARU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '100000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC KALIMANTAN BAGIAN TIMUR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '100000',
				'kd_kantor' => '100300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B BALIKPAPAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '100000',
				'kd_kantor' => '100500',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B SAMARINDA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '100000',
				'kd_kantor' => '100600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BONTANG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '100000',
				'kd_kantor' => '101000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C SANGATTA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '100000',
				'kd_kantor' => '100800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B TARAKAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '100000',
				'kd_kantor' => '100900',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C NUNUKAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '110000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC SULAWESI BAGIAN SELATAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '110000',
				'kd_kantor' => '110100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN B MAKASSAR',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '110000',
				'kd_kantor' => '110300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PAREPARE',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '110000',
				'kd_kantor' => '110400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MALILI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '110000',
				'kd_kantor' => '110600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C KENDARI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '190000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC SULAWESI BAGIAN UTARA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '190000',
				'kd_kantor' => '110800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C PANTOLOAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '190000',
				'kd_kantor' => '110900',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MOROWALI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '190000',
				'kd_kantor' => '111000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C LUWUK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '190000',
				'kd_kantor' => '111100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BITUNG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '190000',
				'kd_kantor' => '111200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MANADO',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '190000',
				'kd_kantor' => '111300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C GORONTALO',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 9,
				'level' => 3,
				'parent' => '190000',
				'kd_kantor' => '111400',
				'nama_kantor' => 'PANGKALAN SARANA OPERASI BEA DAN CUKAI TIPE B PANTOLOAN',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '120000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC MALUKU',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '120000',
				'kd_kantor' => '120100',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C AMBON',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '120000',
				'kd_kantor' => '121000',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C TUAL',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '120000',
				'kd_kantor' => '120200',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C TERNATE',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 6,
				'level' => 2,
				'parent' => '000000',
				'kd_kantor' => '200000',
				'nama_kantor' => 'KANTOR WILAYAH DJBC KHUSUS PAPUA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '120300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C SORONG',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '120400',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MANOKWARI',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '122300',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BABO',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '120600',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C JAYAPURA',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '120800',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C AMAMAPARE',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '120900',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C BIAK',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 7,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '120700',
				'nama_kantor' => 'KANTOR PENGAWASAN DAN PELAYANAN BEA DAN CUKAI TIPE MADYA PABEAN C MERAUKE',
				'active' => true,
				'created_at' => $now,
				'updated_at' => $now,
			],
			[
				'tipe' => 9,
				'level' => 3,
				'parent' => '200000',
				'kd_kantor' => '121100',
				'nama_kantor' => 'PANGKALAN SARANA OPERASI BEA DAN CUKAI TIPE B SORONG',
				'active' => false,
				'created_at' => $now,
				'updated_at' => $now,
			],
		];

		RefKantorBC::insert($data);
	}
}
